name: Test

on: 
  push:
  pull_request:

env:
  GOMODULE111: on

jobs:

  test:
    strategy:
      matrix:
        platform: 
          - ubuntu-latest
          - macos-latest
        # Put the go version in the matrix to support testing on more versions of go in the future
        go:
          - 1.16.x

    runs-on: ${{ matrix.os }}
    name: '${{ matrix.os}} | ${{ matrix.go }}'
    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-${{ matrix-go }}-

      - run: |
          export GOBIN=$HOME/go/bin
          go install github.com/kyoh86/richgo

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: cp $GOOGLE_APPLICATION_CREDENTIALS ~/.config/gcloud/application_default_credentials.json

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        id: install

      - run: richgo test -v ./...
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ""
